name: auto_size_text
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 2.1.1
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/auto_size_text

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: '>=1.9.0 <3.0.0'